# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\voltage_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
from functools import partial
import pyvista as pv
from pyvistaqt import QtInteractor, MainWindow
from reader import load_dataset_mat, create_mesh, draw_map


class Ui_MainWindow(object):
    def __init__(self) -> None:
        filename = "./data/dataset_2.mat"
        points, indices, fields = load_dataset_mat(filename)
        mesh = create_mesh(points, indices)
        voltage = [0 if math.isnan(x) else x for x in fields.bipolar_voltage]
        self.mesh = mesh
        self.voltage = voltage

        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 901, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 510, 901, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 560, 91, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 560, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 21))
        self.menubar.setObjectName("menubar")
        self.menuMesh = QtWidgets.QMenu(self.menubar)
        self.menuMesh.setObjectName("menuMesh")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Sphere = QtWidgets.QAction(MainWindow)
        self.actionAdd_Sphere.setObjectName("actionAdd_Sphere")
        self.menuMesh.addAction(self.actionAdd_Sphere)
        self.menubar.addAction(self.menuMesh.menuAction())

        self.plotter = QtInteractor(self.frame)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "Voltage Map"))
        self.checkBox_2.setText(_translate("MainWindow", "Edges"))
        self.menuMesh.setTitle(_translate("MainWindow", "Mesh"))
        self.actionAdd_Sphere.setText(_translate("MainWindow", "Add Sphere"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
